spring.config.activate.on-profile=dev
spring.application.version=1.0.0-dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.r2dbc.url=${SUPABASE_REACTIVE_URL}
#${SUPABASE_CONNECTION_STRING}
spring.r2dbc.username=${USERNAME}
spring.r2dbc.password=${PASSWORD}
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
spring.flyway-url=${FLYWAY_URL}
spring.flyway.locations=classpath:/db/migrations
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET_SERVER}
#spring.main.allow-circular-references=true
spring.cloud.gcp.project-id=${GCS_PROJECT_ID}
spring.cloud.gcp.credentials.location=classpath:casa-store.json
gcs.bucket-name=${GCS_BUCKET}
gcs.subdirectory=casa
# OAUTH2
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID_GOOGLE}
#  ${CLIENT_ID_GOOGLE}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET_GOOGLE}
#  ${CLIENT_SECRET_GOOGLE}
# TWILIO
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
# MAIL
spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=${USERNAME_MAIL}
spring.mail.password=${PASSWORD_MAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true